### ISSUE TITLE
Support for maven multimodule project

### ISSUE THREAD

**Issue by luandrea** [STAMP-project/botsing-github-app#1]
#### Description

It would be nice to have the app scan automatically the project and collect all the dependencies inside all the modules of the project.

#### Alternatives

An alternative could be to specify the artifactId and groupId and collect the dependencies needed.

**Comment by luandrea** [comment]
This is not necessary anymore because the project is not built anymore, but it will search the artifact directly in Maven Central repository.

**Comment by vmassol** [comment]
> , but it will search the artifact directly in Maven Central repository.

How will that work for projects that don't put their artifacts in maven central? (such as XWiki)

**Comment by luandrea** [comment]
It will not work because it will not be able to find it.

Please add another enhancement here.
